#!/usr/bin/env python3
#desktop only

from os import system, popen, chdir

currentDirectory = popen("cd").read().replace("\n","")
path = "C:\\Program Files\\prop-deepster"
chdir(path)
system("python prop-call -u")
choke = input("\n\nPress Enter to continue")
system(f"cd {currentDirectory}")