#!/usr/bin/env python

from tkinter import *
from tkinter import ttk
import os, time, psutil, socket, subprocess
from signal import *
from datetime import datetime
import pandas as pd

class prop:
    def __init__(self, master):
        self.parent = master
        self.notebook = ttk.Notebook(master) #notebook init
        self.notebook.pack(fill=BOTH, expand=True)
        
        self.frame1 = ttk.Frame(self.notebook) #frame1 ~~ ALL
        self.frame2 = ttk.Frame(self.notebook) #frame2 ~~ CPU
        self.frame3 = ttk.Frame(self.notebook) #frame3 ~~ Memory
        self.frame4 = ttk.Frame(self.notebook) #frame4 ~~ KILL
        self.notebook.add(self.frame1, text='ALL')
        self.notebook.add(self.frame2, text='CPU')
        self.notebook.add(self.frame3, text='Memory')
        self.notebook.add(self.frame4, text='KILL')
        
        #setup ALL ~~ frame 1
        self.frame1child1 = ttk.Frame(self.frame1)
        self.frame1child1.pack(fill=BOTH)
        self.all = Text(self.frame1child1)
        self.all.pack(fill=BOTH)
        self.all.after(500, self.process_refresh_all)
        
        #setup CPU ~~ frame2
        self.frame2child1 = ttk.Frame(self.frame2)
        self.frame2child1.pack(fill=BOTH)
        self.CPU = Text(self.frame2child1)
        self.CPU.pack(fill=BOTH)
        self.CPU.after(1000, self.CPU_refresh)
        
        #setup Memory ~~ frame3
        self.frame3child1 = ttk.Frame(self.frame3)
        self.frame3child1.pack(fill=BOTH)
        self.mem = Text(self.frame3child1)
        self.mem.pack(fill=BOTH)
        self.mem.after(1500, self.mem_refresh)
        
        #setup Kill ~~ frame4
        self.frame4child1 = ttk.Frame(self.frame4)
        self.frame4child1.pack(fill=BOTH)
        self.frame4child1label1 = ttk.Label(self.frame4child1, text='Enter Pid of the process to kill', justify=CENTER)
        self.frame4child1label1.pack()
        self.frame4child2 = ttk.Frame(self.frame4)
        self.frame4child2.pack(fil=BOTH)
        self.frame4child2entry1 = ttk.Entry(self.frame4child2, width=30, justify=CENTER)
        self.frame4child2entry1.pack()
        self.emptyText = StringVar()
        self.emptyText.set('')
        self.frame4child2entry1.config(textvariable=self.emptyText)
        self.frame4child3 = ttk.Frame(self.frame4)
        self.frame4child3.pack(fill=BOTH)
        self.frame4child3button1 = ttk.Button(self.frame4child3, text='[KILL]', command=self.kill)
        self.frame4child3button1.pack()
        self.frame4child4 = ttk.Frame(self.frame4)
        self.frame4child4.pack(fill=BOTH)
        self.killednotification = StringVar()
        self.killednotification.set('')
        self.frame4child4label1 = ttk.Label(self.frame4child4, textvariable=self.killednotification, justify=CENTER)
        self.frame4child4label1.pack()
   
    def process_refresh_all(self):
        allprocess = subprocess.Popen('python prop-call.dat', stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
        allprocess_out, allprocess_err = allprocess.communicate()
        self.all.delete(1.0, END)
        self.all.insert(END, allprocess_out)
        self.all.after(3500, self.process_refresh_all)
    
    def CPU_refresh(self):
        CPU_usage = subprocess.Popen('python prop-call.dat -c \"name,cpu_usage,read_bytes,write_bytes,status,create_time,n_threads,cores\" -s cpu_usage --descending', stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
        CPU_usage_out, CPU_usage_err = CPU_usage.communicate()
        self.CPU.delete(1.0, END)
        self.CPU.insert(END, CPU_usage_out)
        self.CPU.after(2000, self.CPU_refresh)
    
    def mem_refresh(self):
        mem_usage = subprocess.Popen('python prop-call.dat -c \"name,memory_usage,read_bytes,write_bytes,status,create_time,n_threads,cores\" -s memory_usage --descending', stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
        mem_usage_out, mem_usage_err = mem_usage.communicate()
        self.mem.delete(1.0, END)
        self.mem.insert(END, mem_usage_out)
        self.mem.after(2500, self.mem_refresh)
    
    def kill(self):
        os.kill(int(self.frame4child2entry1.get().strip()), SIGINT)
        self.killednotification.set(f'Killed process: {self.frame4child2entry1.get()}')
        self.frame4child4label1.after(2000, self.clean_kill_notification)
    
    def clean_kill_notification(self):
        self.killednotification.set('')
        self.emptyText.set('')
        
def main():
    hostname = socket.gethostname()
    root = Tk()
    root.title(f"Process Plot ~ running on {hostname}")
    root.geometry("1100x410")
    app = prop(root)
    root.mainloop()
    
if __name__=='__main__':main()