#!/usr/bin/env python3

from os import system, popen, chdir
from sys import argv

currentDirectory = popen("cd").read().replace("\n","")
path = "C:\\Program Files\\prop-deepster"
chdir(path)
argLength = len(argv)
argss=""
for i in range(1,argLength):
    argss=argss+" "+argv[i]
system(f"python prop-call.dat -u{argss}")
choke = input("\n\nPress Enter to continue")
system(f"cd {currentDirectory}")