#!/usr/bin/env python

from tkinter import *
from tkinter import ttk
import os, time, psutil, socket, subprocess
from datetime import datetime
import pandas as pd

class prop:
    def __init__(self, master):
        self.parent = master
        self.notebook = ttk.Notebook(master) #notebook init
        self.notebook.pack(fill=BOTH, expand=True)
        
        self.frame1 = ttk.Frame(self.notebook) #frame1 ~~ ALL
        self.frame2 = ttk.Frame(self.notebook) #frame2 ~~ CPU
        self.frame3 = ttk.Frame(self.notebook) #frame3 ~~ Memory
        self.frame4 = ttk.Frame(self.notebook) #frame4 ~~ KILL
        self.notebook.add(self.frame1, text='ALL')
        self.notebook.add(self.frame2, text='CPU')
        self.notebook.add(self.frame3, text='Memory')
        self.notebook.add(self.frame4, text='KILL')
        
        #setup ALL ~~ frame 1
        self.frame1child1 = ttk.Frame(self.frame1)
        self.frame1child1.pack(fill=BOTH)
        self.all = Text(self.frame1child1)
        self.all.pack(fill=BOTH)
        allprocess = subprocess.Popen('python prop-call.dat', stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
        allprocess_out, allprocess_err = allprocess.communicate()
        self.all.insert(END, allprocess_out)
        self.all.after(3500, self.process_refresh_all)
        
        #setup CPU ~~ frame2
        self.frame2child2 = ttk.Frame(self.frame2)
        self.frame2child2.pack(fill=BOTH)
        self.CPU = Text(self.frame2child2)
        self.CPU.pack(fill=BOTH)
        CPU_usage = subprocess.Popen('python prop-call.dat -c \"name,cpu_usage,read_bytes,write_bytes,status,create_time,n_threads,cores\" -s cpu_usage --descending', stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
        CPU_usage_out, CPU_usage_err = CPU_usage.communicate()
        self.CPU.insert(END, CPU_usage_out)
        self.CPU.after(2000, self.CPU_refresh)     
    
    def process_refresh_all(self):
        allprocess = subprocess.Popen('python prop-call.dat', stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
        allprocess_out, allprocess_err = allprocess.communicate()
        self.all.delete(1.0, END)
        self.all.insert(END, allprocess_out)
        self.all.after(3500, self.process_refresh_all)
    
    def CPU_refresh(self):
        CPU_usage = subprocess.Popen('python prop-call.dat -c \"name,cpu_usage,read_bytes,write_bytes,status,create_time,n_threads,cores\" -s cpu_usage --descending', stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
        CPU_usage_out, CPU_usage_err = CPU_usage.communicate()
        self.CPU.delete(1.0, END)
        self.CPU.insert(END, CPU_usage_out)
        self.CPU.after(2000, self.process_refresh_all)
        
def main():
    hostname = socket.gethostname()
    root = Tk()
    root.title(f"Process Plot ~ {hostname}")
    root.geometry("1140x425")
    app = prop(root)
    root.mainloop()
    
if __name__=='__main__':main()