#!/usr/bin/env python

from tkinter import *
from tkinter import ttk
import os, time, psutil, socket, subprocess
from signal import *
from datetime import datetime
import pandas as pd

class prop:
    def __init__(self, master, df):
        self.parent = master
        
        #setup notebook
        self.notebook = ttk.Notebook(master) #notebook init
        self.notebook.pack(fill=BOTH, expand=True)
        
        self.frame1 = ttk.Frame(self.notebook) #frame1 ~~ ALL
        self.frame2 = ttk.Frame(self.notebook) #frame2 ~~ CPU
        self.frame3 = ttk.Frame(self.notebook) #frame3 ~~ Memory
        self.frame4 = ttk.Frame(self.notebook) #frame4 ~~ KILL
        self.notebook.add(self.frame1, text='ALL')
        self.notebook.add(self.frame2, text='CPU')
        self.notebook.add(self.frame3, text='Memory')
        self.notebook.add(self.frame4, text='KILL')
        
        #setup ALL ~~ frame 1
        self.frame1child1 = ttk.Frame(self.frame1)
        self.frame1child1.pack(fill=BOTH)
        self.all = Text(self.frame1child1)
        self.all.pack(fill=BOTH)
        self.all.insert(END, df.to_string())
        
        #setup CPU ~~ frame2
        self.frame2child1 = ttk.Frame(self.frame2)
        self.frame2child1.pack(fill=BOTH)
        self.CPU = Text(self.frame2child1, wrap='none')
        self.CPU.pack(fill=BOTH)
        cpu_df = df[['pid', 'name', 'cpu_usage', 'read_bytes', 'write_bytes', 'status', 'create_time', 'n_threads', 'cores']].sort_values(by='cpu_usage', ascending=False)
        self.CPU.insert(END, cpu_df.to_string())
        
        #setup Memory ~~ frame3
        self.frame3child1 = ttk.Frame(self.frame3)
        self.frame3child1.pack(fill=BOTH)
        self.mem = Text(self.frame3child1)
        self.mem.pack(fill=BOTH)
        mem_df = df[['pid', 'name', 'memory_usage', 'read_bytes', 'write_bytes', 'status', 'create_time', 'n_threads', 'cores']].sort_values(by='memory_usage', ascending=False)
        self.mem.insert(END, mem_df.to_string())

        #setup Kill ~~ frame4
        self.frame4child1 = ttk.Frame(self.frame4)
        self.frame4child1.pack(fill=BOTH)
        self.frame4child1label1 = ttk.Label(self.frame4child1, text='Enter Pid of the process to kill', justify=CENTER)
        self.frame4child1label1.pack()
        self.frame4child2 = ttk.Frame(self.frame4)
        self.frame4child2.pack(fil=BOTH)
        self.frame4child2entry1 = ttk.Entry(self.frame4child2, width=30, justify=CENTER)
        self.frame4child2entry1.pack()
        self.emptyText = StringVar()
        self.emptyText.set('')
        self.frame4child2entry1.config(textvariable=self.emptyText)
        self.frame4child3 = ttk.Frame(self.frame4)
        self.frame4child3.pack(fill=BOTH)
        self.frame4child3button1 = ttk.Button(self.frame4child3, text='[KILL]', command=self.kill)
        self.frame4child3button1.pack()
        self.frame4child4 = ttk.Frame(self.frame4)
        self.frame4child4.pack(fill=BOTH)
        self.killednotification = StringVar()
        self.killednotification.set('')
        self.frame4child4label1 = ttk.Label(self.frame4child4, textvariable=self.killednotification, justify=CENTER)
        self.frame4child4label1.pack()
        
        #updater
        self.parent.update()
        df = updater()
        self.all_update(df=df)
    
    def all_update(self, df):
        self.all.delete(1.0, END)
        self.all.insert(END, df.to_string())
        cpu_df = df[['pid', 'name', 'cpu_usage', 'read_bytes', 'write_bytes', 'status', 'create_time', 'n_threads', 'cores']].sort_values(by='cpu_usage', ascending=False)
        self.CPU.delete(1.0, END)
        self.CPU.insert(END, cpu_df.to_string())
        mem_df = df[['pid', 'name', 'memory_usage', 'read_bytes', 'write_bytes', 'status', 'create_time', 'n_threads', 'cores']].sort_values(by='memory_usage', ascending=False)
        self.mem.delete(1.0, END)
        self.mem.insert(END, mem_df.to_string())
        self.parent.update()
        df = updater()
        self.all.after(50000, self.all_update(df))
        
    def kill(self):
        os.kill(int(self.frame4child2entry1.get().strip()), SIGINT)
        self.killednotification.set(f'Killed process: {self.frame4child2entry1.get()}')
        self.frame4child4label1.after(2000, self.clean_kill_notification)
    
    def clean_kill_notification(self):
        self.killednotification.set('')
        self.emptyText.set('')
        
def updater():
    first_output = os.system('python prop-call2.dat -n 0')
    df = pd.read_csv('C:\\Program Files\\prop-deepster\\update.csv')
    return df

def main():
    if os.path.exists("C:\\Program Files\\prop-deepster\\update.csv"):
        os.remove("C:\\Program Files\\prop-deepster\\update.csv")
    df = updater()
    time.sleep(3)
    hostname = socket.gethostname()
    root = Tk()
    root.title(f"Process Plot ~ running on {hostname}")
    root.geometry("1200x410")
    app = prop(master=root, df=df)
    root.mainloop()

if __name__=='__main__':
    try:
        main()
    except TclError:
        pass