#!/usr/bin/env python

from tkinter import *
from tkinter import ttk
import os, time, psutil, socket, subprocess
from signal import *
from datetime import datetime
import pandas as pd

class prop:
    def __init__(self, master, df) -> None:
        self.parent = master
        

def main():
    first_output = os.system('python prop-call2.dat')

if __name__=='__main__':main()